  char* menu1[]={"DESARME","SABOTAGEM","DOMINACAO", "CUT THE WIRE", "CONFIG"      };
  char* menu2[]={"CONFIG JOGO","CONFIG SOM", "TESTE RELE", "TESTE AUTO"      };   
  char* GAME_TIME="TEMPO DE JOGO:";
  char* BOMB_TIME="TEMPO BOMBA:";
  char* ZERO_MINUTES="00 minutos";
  char* ARM_TIME="ATIVAR EM:";
  char* ZERO_SECS="00 segundos";
  char* ENABLE_SOUND="ATIVAR SOM?";
  char* YES_OR_NOT="A : SIM B : NAO";
  char* ENABLE_RELAYPIN="ATIVAR RELE?";
  char* ENABLE_TESTEPIN="AVISO DES/ARMADA?";
  char* ENABLE_CODE="ATIVAR SENHA?";
  char* GAME_TIME_TOP="TEMPO DE JOGO";
  char* ARMING_BOMB = "ARMANDO BOMBA";
  char* ENTER_CODE = "INSERIR SENHA";
  char* CODE_ERROR = "SENHA ERRADA";
  char* BOMB_ARMED = "BOMBA ARMADA";
  char* DETONATION_IN = "DETONANDO EM";
  char* DISARMING = "DESARMANDO BOMBA" ;
  char* DISARM = "DESARMADA";
  char* GAME_OVER = "FIM DE JOGO";
  char* DEFENDERS_WIN = "DEFESA GANHA";
  char* SABOTAGE_FAIL= "SABOTAGEM FALHOU";
                   
  
